// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticumProjects.Server.Data;

#nullable disable

namespace PracticumProjects.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260804054904_TopicSubmissionsAndSubmissionFiles")]
    partial class TopicSubmissionsAndSubmissionFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PracticumProjects.Models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("semester_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("SemesterType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("semester_type");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("SemesterId");

                    b.ToTable("semesters");
                });

            modelBuilder.Entity("PracticumProjects.Server.Models.GroupMember", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<int?>("StudentId1")
                        .HasColumnType("int")
                        .HasColumnName("student_id1");

                    b.Property<int?>("StudentId2")
                        .HasColumnType("int")
                        .HasColumnName("student_id2");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int")
                        .HasColumnName("supervisor_id");

                    b.HasKey("GroupId");

                    b.HasIndex("StudentId1");

                    b.HasIndex("StudentId2");

                    b.HasIndex("SupervisorId");

                    b.ToTable("group_members");
                });

            modelBuilder.Entity("PracticumProjects.Server.Models.SubmissionFile", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("file_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FileId"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("ModuleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("module_type");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploaded_at");

                    b.HasKey("FileId");

                    b.HasIndex("ModuleType", "EntityId");

                    b.ToTable("submission_files");
                });

            modelBuilder.Entity("PracticumProjects.Server.Models.ThesisGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("group_name");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("semester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("GroupId");

                    b.HasIndex("SemesterId");

                    b.ToTable("thesis_groups");
                });

            modelBuilder.Entity("PracticumProjects.Server.Models.TopicSubmission", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("topic_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TopicId"));

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("abstract");

                    b.Property<string>("CoordinatorFeedback")
                        .HasColumnType("longtext")
                        .HasColumnName("coordinator_feedback");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("Keywords")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("keywords");

                    b.Property<string>("Objectives")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("objectives");

                    b.Property<string>("ProblemStatement")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("problem_statement");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("SupervisorFeedback")
                        .HasColumnType("longtext")
                        .HasColumnName("supervisor_feedback");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("TopicId");

                    b.HasIndex("GroupId");

                    b.ToTable("topic_submissions");
                });

            modelBuilder.Entity("PracticumProjects.Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsProfileCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PracticumProjects.Server.Models.GroupMember", b =>
                {
                    b.HasOne("PracticumProjects.Server.Models.ThesisGroup", "ThesisGroup")
                        .WithOne("GroupMember")
                        .HasForeignKey("PracticumProjects.Server.Models.GroupMember", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticumProjects.Server.Models.User", "Student1")
                        .WithMany()
                        .HasForeignKey("StudentId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PracticumProjects.Server.Models.User", "Student2")
                        .WithMany()
                        .HasForeignKey("StudentId2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PracticumProjects.Server.Models.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Student1");

                    b.Navigation("Student2");

                    b.Navigation("Supervisor");

                    b.Navigation("ThesisGroup");
                });

            modelBuilder.Entity("PracticumProjects.Server.Models.ThesisGroup", b =>
                {
                    b.HasOne("PracticumProjects.Models.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("PracticumProjects.Server.Models.TopicSubmission", b =>
                {
                    b.HasOne("PracticumProjects.Server.Models.ThesisGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PracticumProjects.Server.Models.ThesisGroup", b =>
                {
                    b.Navigation("GroupMember");
                });
#pragma warning restore 612, 618
        }
    }
}
