// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticumProjects.Server.Data;

#nullable disable

namespace PracticumProjects.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260803050155_AddThesisGroupsAndMembers")]
    partial class AddThesisGroupsAndMembers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PracticumProjects.Server.Models.GroupMember", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<int?>("StudentId1")
                        .HasColumnType("int")
                        .HasColumnName("student_id1");

                    b.Property<int?>("StudentId2")
                        .HasColumnType("int")
                        .HasColumnName("student_id2");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int")
                        .HasColumnName("supervisor_id");

                    b.HasKey("GroupId");

                    b.HasIndex("StudentId1");

                    b.HasIndex("StudentId2");

                    b.HasIndex("SupervisorId");

                    b.ToTable("group_members");
                });

            modelBuilder.Entity("PracticumProjects.Server.Models.ThesisGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("group_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("GroupId");

                    b.ToTable("thesis_groups");
                });

            modelBuilder.Entity("PracticumProjects.Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsProfileCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PracticumProjects.Server.Models.GroupMember", b =>
                {
                    b.HasOne("PracticumProjects.Server.Models.ThesisGroup", "ThesisGroup")
                        .WithOne("GroupMember")
                        .HasForeignKey("PracticumProjects.Server.Models.GroupMember", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticumProjects.Server.Models.User", "Student1")
                        .WithMany()
                        .HasForeignKey("StudentId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PracticumProjects.Server.Models.User", "Student2")
                        .WithMany()
                        .HasForeignKey("StudentId2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PracticumProjects.Server.Models.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Student1");

                    b.Navigation("Student2");

                    b.Navigation("Supervisor");

                    b.Navigation("ThesisGroup");
                });

            modelBuilder.Entity("PracticumProjects.Server.Models.ThesisGroup", b =>
                {
                    b.Navigation("GroupMember");
                });
#pragma warning restore 612, 618
        }
    }
}
